//Query category
import './query/is_alpha';
import './query/is_alpha_digit';
import './query/is_blank';
import './query/is_digit';
import './query/is_empty';
import './query/is_ending_with';
import './query/is_lower_case';
import './query/is_numeric';
import './query/is_starting_with';
import './query/is_string';
import './query/is_upper_case';